from __future__ import annotations

from .schemas import ChatMessage

_DEFAULT_MAX_MESSAGES = 200  # per session; oldest messages are dropped when exceeded


class ConversationMemory:
    """Stores per-session chat history so every model has access to prior turns.

    History is keyed by ``session_id`` (a UUID string supplied by the client or
    auto-generated by the gateway on the first turn).  Only the most recent
    ``max_messages`` messages are retained per session to prevent unbounded
    growth; once exceeded the oldest messages are silently dropped from the
    front of the list.  This means very long conversations may lose early
    context — callers that require full history should reduce their turn
    frequency or increase ``max_messages`` at construction time.
    """

    def __init__(self, max_messages: int = _DEFAULT_MAX_MESSAGES) -> None:
        self._max_messages = max_messages
        self._sessions: dict[str, list[ChatMessage]] = {}

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def get_history(self, session_id: str) -> list[ChatMessage]:
        """Return the full message history for *session_id* (may be empty)."""
        return list(self._sessions.get(session_id, []))

    def list_sessions(self) -> list[str]:
        return list(self._sessions.keys())

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def append_turn(self, session_id: str, messages: list[ChatMessage]) -> None:
        """Append *messages* to the session and enforce the rolling window."""
        history = self._sessions.setdefault(session_id, [])
        history.extend(messages)
        if len(history) > self._max_messages:
            # Drop oldest messages to stay within the window.
            del history[: len(history) - self._max_messages]

    # ------------------------------------------------------------------
    # Management
    # ------------------------------------------------------------------

    def clear(self, session_id: str) -> bool:
        """Delete the session.  Returns True if the session existed."""
        if session_id in self._sessions:
            del self._sessions[session_id]
            return True
        return False
